version: "3"
services:
  postgres:
    image: library/postgres:13
    container_name: postgres
    restart: on-failure
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: postgres
    volumes:
      - db-test-data:/var/lib/postgresql/data
      - ./postgres:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
  
  gateway:
    image: swanpoi/gateway:latest
    container_name: gateway
    restart: on-failure
    environment:
      HOST: "0.0.0.0"
      PORT: "8080"
      REDIS_HOST: redis
      REDIS_PORT: "6379"
      CAR_URL: http://cars:8070/api/v1
      RENTAL_URL: http://rental:8060/api/v1
      PAYMENT_URL: http://payment:8050/api/v1
    build:
      context: src/gateway
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  cars:
    image: swanpoi/car-service:latest
    container_name: car
    restart: on-failure
    environment:
      HOST: "0.0.0.0"
      PORT: "8070"
      DB_HOST: postgres
      DB_PORT: "5432"
      DB_PASSWORD: "postgres"
      DB_USER: postgres
      DB_NAME: cars
    build:
      context: src/car
      dockerfile: Dockerfile
    ports:
      - "8070:8070"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  rental:
    image: swanpoi/rental-service:latest
    container_name: rental
    restart: on-failure
    environment:
      HOST: "0.0.0.0"
      PORT: "8060"
      DB_HOST: postgres
      DB_PORT: "5432"
      DB_PASSWORD: "postgres"
      DB_USER: postgres
      DB_NAME: rentals
    build:
      context: src/rental
      dockerfile: Dockerfile
    ports:
      - "8060:8060"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  payment:
    image: swanpoi/payment-service:latest
    container_name: payment
    restart: on-failure
    environment:
      HOST: "0.0.0.0"
      PORT: "8050"
      DB_HOST: postgres
      DB_PORT: "5432"
      DB_PASSWORD: "postgres"
      DB_USER: postgres
      DB_NAME: payments
    build:
      context: src/payment
      dockerfile: Dockerfile
    ports:
      - "8050:8050"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

volumes:
  db-test-data: