apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.redis.svc.name }}
  labels:
    app: {{ .Values.redis.name }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.redis.name }}
  ports:
  - port: {{ .Values.redis.svc.port }}
    targetPort: 6379
    name: {{ .Values.redis.name }}