apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.postgres.configMap.name }}
  labels:
    app: {{ .Values.postgres.name }}
data:
  00-create-user.sql: |
    CREATE ROLE program WITH PASSWORD 'test';
    ALTER ROLE program WITH LOGIN;
    
  01-create-databases.sql: |
    CREATE DATABASE cars;
    GRANT ALL PRIVILEGES ON DATABASE cars TO program;

    CREATE DATABASE rentals;
    GRANT ALL PRIVILEGES ON DATABASE rentals TO program;

    CREATE DATABASE payments;
    GRANT ALL PRIVILEGES ON DATABASE payments TO program;

  02-cars-schema.sql: |
    \c cars;
    CREATE TABLE IF NOT EXISTS cars
    (
        id                  SERIAL PRIMARY KEY,
        car_uid             uuid UNIQUE NOT NULL,
        brand               VARCHAR(80) NOT NULL,
        model               VARCHAR(80) NOT NULL,
        registration_number VARCHAR(20) NOT NULL,
        power               INT,
        price               INT         NOT NULL,
        type                VARCHAR(20) CHECK (type IN ('SEDAN', 'SUV', 'MINIVAN', 'ROADSTER')),
        availability        BOOLEAN     NOT NULL
    );

    INSERT INTO cars (car_uid, brand, model, registration_number, power, price, type, availability) VALUES
    ('109b42f3-198d-4c89-9276-a7520a7120ab', 'Mercedes Benz', 'GLA 250', 'ЛО777Х799', 249, 3500, 'SEDAN', true)
    ON CONFLICT DO NOTHING;
    ALTER TABLE cars OWNER TO program;

  03-payments-schema.sql: |
    \c payments;
    CREATE TABLE IF NOT EXISTS payment
    (
        id          SERIAL PRIMARY KEY,
        payment_uid uuid        NOT NULL,
        status      VARCHAR(20) NOT NULL CHECK (status IN ('PAID', 'CANCELED')),
        price       INT         NOT NULL
    );
    ALTER TABLE payment OWNER TO program;

  04-rentals-schema.sql: |
    \c rentals;
    CREATE TABLE IF NOT EXISTS rental
    (
        id          SERIAL PRIMARY KEY,
        rental_uid  uuid UNIQUE              NOT NULL,
        username    VARCHAR(80)              NOT NULL,
        payment_uid uuid                     NOT NULL,
        car_uid     uuid                     NOT NULL,
        date_from   TIMESTAMP WITH TIME ZONE NOT NULL,
        date_to     TIMESTAMP WITH TIME ZONE NOT NULL,
        status      VARCHAR(20)              NOT NULL CHECK (status IN ('IN_PROGRESS', 'FINISHED', 'CANCELED'))
    );
    ALTER TABLE rental OWNER TO program;
