apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.postgres.secret.name }}
  labels:
    app: {{ .Values.postgres.name }}
type: Opaque
data:
  postgres-username: {{ .Values.postgres.credentials.user | b64enc }}
  postgres-password: {{ .Values.postgres.credentials.password | b64enc }}