apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.postgres.svc.name }}
  labels:
    app: {{ .Values.postgres.name }}
spec:
  clusterIP: None
  selector:
    app: {{ .Values.postgres.name }}
  ports:
  - port: {{ .Values.postgres.svc.port }}
    name: {{ .Values.postgres.name }} 