apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: "{{ .Values.postgres.name }}-set"
  labels:
    app: {{ .Values.postgres.name }}
spec:
  serviceName: {{ .Values.postgres.svc.name }}
  replicas: {{ .Values.postgres.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.postgres.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.postgres.name }}
    spec:
      containers:
      - name: {{ .Values.postgres.name }}
        image: "{{ .Values.postgres.image.repository }}:{{ .Values.postgres.image.tag }}"
        imagePullPolicy: {{ .Values.postgres.image.pullPolicy }}
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: {{ .Values.postgres.secret.name }}
              key: postgres-username
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.postgres.secret.name }}
              key: postgres-password
        - name: POSTGRES_DB
          value: {{ .Values.postgres.database.name }}
        ports:
        - containerPort: {{ .Values.postgres.svc.port }}
          name: {{ .Values.postgres.name }}
        livenessProbe:
          exec:
            command: ["sh", "-c", "pg_isready -U {{ .Values.postgres.credentials.user }}"]
          initialDelaySeconds: 10
          periodSeconds: 5
        readinessProbe:
          exec:
            command: ["sh", "-c", "pg_isready -U {{ .Values.postgres.credentials.user }}"]
          initialDelaySeconds: 5
          periodSeconds: 5
        volumeMounts:
        - name: db-data
          mountPath: {{ .Values.postgres.persistence.mountPath }}
        - name: init-scripts
          mountPath: /docker-entrypoint-initdb.d
      volumes:
      - name: init-scripts
        configMap:
          name: {{ .Values.postgres.configMap.name }}
  volumeClaimTemplates:
  - metadata:
      name: db-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: {{ .Values.postgres.persistence.size }}




